#!/usr/bin/env bash
# =============================================================
# setup_cron.sh — AI Job Hunter: Local Cron Setup
# =============================================================
# Run this ONCE to:
#   1. Verify your .env file exists with real keys
#   2. Create run_local.sh (the cron wrapper)
#   3. Install the optimised cron schedule into crontab
#
# Usage:
#   chmod +x setup_cron.sh
#   ./setup_cron.sh
#
# To remove all job hunter cron entries later:
#   crontab -l | grep -v "AI Job Hunter" | grep -v "run_local.sh" | crontab -
# =============================================================

set -euo pipefail

# ── Paths ──────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_PYTHON="$SCRIPT_DIR/venv/bin/python"
JOB_SCRIPT="$SCRIPT_DIR/job_hunter.py"
RUN_SCRIPT="$SCRIPT_DIR/run_local.sh"
LOG_FILE="$SCRIPT_DIR/cron.log"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
CRON_MARKER="# AI Job Hunter"

# ── Colours ────────────────────────────────────────────────────
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"   # reset

ok()   { echo -e "${GREEN}✅  $1${NC}"; }
warn() { echo -e "${YELLOW}⚠️   $1${NC}"; }
fail() { echo -e "${RED}❌  $1${NC}"; exit 1; }

echo ""
echo "======================================================="
echo "  AI Job Hunter — Local Cron Setup"
echo "======================================================="
echo ""

# ── 1. Check .env ───────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
    warn ".env not found — creating from template."
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    echo ""
    echo "  👉  Edit $ENV_FILE and fill in your real keys:"
    echo "       GEMINI_API_KEY"
    echo "       OPENROUTER_API_KEY"
    echo "       GROQ_API_KEY"
    echo "       TELEGRAM_BOT_TOKEN"
    echo "       TELEGRAM_CHAT_ID"
    echo ""
    echo "  Then re-run this script: ./setup_cron.sh"
    echo ""
    exit 0
fi

# Warn if any key is still a placeholder
if grep -q "your_.*_here" "$ENV_FILE" 2>/dev/null; then
    warn "Some keys in .env still have placeholder values."
    warn "The cron will be installed but may fail to run until keys are filled."
    echo ""
fi
ok ".env found"

# ── 2. Check venv ───────────────────────────────────────────────
if [ ! -f "$VENV_PYTHON" ]; then
    fail "venv not found at $SCRIPT_DIR/venv/
   Recreate it with:
     ~/.asdf/installs/python/3.12.8/bin/python3.12 -m venv venv
     venv/bin/pip install -r requirements.txt"
fi
ok "venv found → $($VENV_PYTHON --version)"

# ── 3. Create run_local.sh ──────────────────────────────────────
cat > "$RUN_SCRIPT" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by setup_cron.sh — do not edit manually.
# Re-run setup_cron.sh to regenerate.
set -euo pipefail

cd "$SCRIPT_DIR"

{
  echo ""
  echo "=== Run started: \$(date '+%Y-%m-%d %H:%M:%S %Z') ==="
  "$VENV_PYTHON" "$JOB_SCRIPT"
  echo "=== Run finished: \$(date '+%Y-%m-%d %H:%M:%S %Z') ==="
} >> "$LOG_FILE" 2>&1
WRAPPER

chmod +x "$RUN_SCRIPT"
ok "Created run_local.sh"

# ── 4. Install cron schedule ────────────────────────────────────
# Remove any previously installed AI Job Hunter entries
TMP_CRON=$(mktemp)
(crontab -l 2>/dev/null || true) \
    | grep -v "$CRON_MARKER" \
    | grep -v "run_local.sh" \
    > "$TMP_CRON"

cat >> "$TMP_CRON" <<SCHEDULE

$CRON_MARKER — Weekdays (Mon-Fri): every 2h from 09:30 to 23:30 IST
30 9,11,13,15,17,19,21,23 * * 1-5 $RUN_SCRIPT

$CRON_MARKER — Weekends (Sat-Sun): 12:00 PM, 7:00 PM, 11:30 PM IST
0 12,19 * * 0,6 $RUN_SCRIPT
30 23 * * 0,6 $RUN_SCRIPT
SCHEDULE

crontab "$TMP_CRON"
rm -f "$TMP_CRON"

ok "Cron schedule installed"

# ── 5. Summary ──────────────────────────────────────────────────
echo ""
echo "======================================================="
echo "  Schedule (all times IST — local machine must be on)"
echo "======================================================="
echo ""
echo "  📅 Weekdays (Mon–Fri):"
echo "     09:30  11:30  13:30  15:30  17:30  19:30  21:30  23:30"
echo ""
echo "  📅 Weekends (Sat–Sun):"
echo "     12:00 PM    07:00 PM    11:30 PM"
echo ""
echo "  📄 Logs  → tail -f $LOG_FILE"
echo "  🧪 Test  → $RUN_SCRIPT"
echo ""
echo "  Verify cron entries:"
echo "     crontab -l"
echo ""
echo "  Remove all job hunter cron entries:"
echo "     crontab -l | grep -v 'AI Job Hunter' | grep -v 'run_local.sh' | crontab -"
echo ""
ok "All done. AI Job Hunter cron is live."
echo ""
